services:
  drawdb:
    image: node:23-alpine
    container_name: drawdb
    ports:
      - 5173:5173
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install -g npm@11.7.0 && npm install && npm run dev -- --host --port 5173"
    networks:
      - default

networks:
  default:
    driver: bridge
